name: jibme
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.10.8


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_launcher_icons: ^0.14.4
  cupertino_icons: ^1.0.8
  iconsax: ^0.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0


flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/img/logo.png


  fonts:
    - family: Dana
      fonts:
        - asset: assets/font/dana/DanaFaNum-Bold.ttf
          weight: 700
        - asset: assets/font/dana/DanaFaNum-DemiBold.ttf
          weight: 600
        - asset: assets/font/dana/DanaFaNum-Regular.ttf
          weight: 400
        - asset: assets/font/dana/DanaFaNum-Light.ttf
          weight: 300